spring:
  application:
    name:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql:
    show-sql: true

springdoc:
  enabled:
  api-docs:
    path:
  default-consumes-media-type:
  default-produces-media-type:
  version:
  swagger-ui:
    path:
    defaultModelsExpandDepth:
